export const dummyData = [
  {
    id: 1,
    sehir: "Gaziantep",
    personelAdi: ["Sümeyra Al", "Canan Tütünen"],
    telefonNumaralari: ["0532 330 16 33", "0539 774 35 75"],
    ulasilanKisi: 1000,
    aracSayisi: {
      binekArac: 1,
      geziciKaravan: 0,
    },
    merkezler: [
      "Nurdağı 1 Konteyner Kenti - Görüşme konteynerı",
      "Mobil Ekip (Nurdağı B-1 C1, TOKİ Konteyner Eğitim Kampüsü, Ahbap Okulları, Nurdağı 2, Fatih Mah. Yeni Mah. Kurudere Mah. )",
    ],
    isbirlikciKurumlar: [
      "WHR",
      "AÇEV",
      "ASHB",
      "Sağlık Bakanlığı",
      "GASMEK",
      "Halk Eğitim Merkezi",
      "TOG",
      "Gaziantep Yardım Vakfı",
      "Empati Derneği",
      "KAÇUV",
      "Diyanet",
      "Yöret-Roman Diyalog Ağı - Sıfır Ayrımcılık Derneği( işbirliği için iletişime geçildi).",
    ],
    coordinates: [37.38000011, 37.0600001],
  },
  {
    id: 2,
    sehir: "Adıyaman",
    personelAdi: [
      "Gizem Yılmaz",
      "Deniz Onuk",
      "Sinan Türkmen",
      "Evin Körsu",
      "Pınar Avcıl",
      "Havvanur Mercimek",
      "Merve Nur Kazgı",
    ],
    telefonNumaralari: [""],
    ulasilanKisi: 236,
    aracSayisi: {
      binekArac: 0,
      geziciKaravan: 0,
    },
    merkezler: [
      "Mersin Büyükşehir Belediyesi'nin Konteyner Kenti'nde K12 çalışma ve yaşam ofisi bulunmakta. Alt yapı çalışmalarının bitmesi bekleniyor.",
    ],
    isbirlikciKurumlar: [
      "Aile ve Sosyal Hizmetler Bakanlığı",
      "AÇEV",
      "UNICEF",
    ],
    coordinates: [38.28, 37.75],
  },
  {
    id: 3,
    sehir: "Kahramanmaraş",
    personelAdi: ["Yarencan Çingir", "Ayça Dağılan", "Gözde Murt"],
    telefonNumaralari: ["0549 553 21 00"],
    ulasilanKisi: 24,
    aracSayisi: {
      binekArac: 0,
      geziciKaravan: 0,
    },
    merkezler: [
      "İzmit & Nilüfer Belediyesi Çadırkent - Kahramanmaraş, Onikişubat",
      "Doğa Koleji - Kahramanmaraş, Onikişubat",
    ],
    isbirlikciKurumlar: ["İzmit Belediyesi"],
    coordinates: [36.93, 37.58],
  },
  {
    id: 4,
    sehir: "Hatay/İskenderun",
    personelAdi: [
      "Sergen Tut",
      "Ebru Akkoyun",
      "Tilbe Yiğit",
      "Ayşe Baykara",
      "Fatma Boz",
      "Feyza Nur Ak",
      "Mehmet Zekeriya Çinçinoğlu",
      "Büşra Basık",
      " Zeynep Gültenkilisli",
    ],
    telefonNumaralari: ["0533 289 00 61", "0535 628 90 52"],
    ulasilanKisi: 524,
    aracSayisi: {
      binekArac: 1,
      geziciKaravan: 2,
    },
    merkezler: [
      "İBB Afet Koordinasyon Merkezi",
      "Harbiye/Hidropark Çadırkent",
      "Samandağ konteyner kent",
      "Orhanlı konteyner kent",
    ],
    isbirlikciKurumlar: [
      "İzmit Belediyesi",
      "Mor Yerleşke",
      "Samandağ Belediyesi",
      "Sunanın Kızları",
      "Maya",
      "AÇEV",
      "İBB",
      "MSF",
      "UNICEF",
      "Hayata Destek Derneği",
      "World Human Relief",
    ],
    coordinates: [36.18, 36.58],
  },
  {
    id: 6,
    sehir: "Osmaniye",
    personelAdi: ["Sümeyra Sülü", "Derya Genç", "Sevgi Tarhan"],
    telefonNumaralari: [""],
    ulasilanKisi: 200,
    aracSayisi: {
      binekArac: 0,
      geziciKaravan: 0,
    },
    merkezler: ["Mobil Ekip"],
    isbirlikciKurumlar: [],
    coordinates: [36.25, 37.06],
  },
  {
    id: 7,
    sehir: "Malatya",
    personelAdi: [""],
    telefonNumaralari: [""],
    ulasilanKisi: 200,
    aracSayisi: {
      binekArac: 0,
      geziciKaravan: 0,
    },
    merkezler: ["Mobil Ekip"],
    isbirlikciKurumlar: [],
    coordinates: [38.31, 38.34],
  },
  {
    id: 8,
    sehir: "Diyarbakır",
    personelAdi: ["Şevval Çoban"],
    telefonNumaralari: [""],
    ulasilanKisi: 200,
    aracSayisi: {
      binekArac: 0,
      geziciKaravan: 0,
    },
    merkezler: ["Mobil Ekip"],
    isbirlikciKurumlar: [],
    coordinates: [40.24, 37.9],
  },
  {
    id: 9,
    sehir: "Şanlıurfa",
    personelAdi: ["Şevval Çoban"],
    telefonNumaralari: [],
    ulasilanKisi: 200,
    aracSayisi: {
      binekArac: 0,
      geziciKaravan: 0,
    },
    merkezler: ["Mobil Ekip"],
    isbirlikciKurumlar: [],
    coordinates: [40.24, 37.9],
  },
];
